"""add_cost_management

Revision ID: 2e4d47d8c88e
Revises: 755249c03e1d
Create Date: 2026-01-27 21:07:10.472467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4d47d8c88e'
down_revision: Union[str, Sequence[str], None] = '755249c03e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('default_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_categories_id'), 'cost_categories', ['id'], unique=False)
    op.create_index(op.f('ix_cost_categories_name'), 'cost_categories', ['name'], unique=True)
    op.create_table('product_cost_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('cost_category_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cost_category_id'], ['cost_categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_cost_components_id'), 'product_cost_components', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_cost_components_id'), table_name='product_cost_components')
    op.drop_table('product_cost_components')
    op.drop_index(op.f('ix_cost_categories_name'), table_name='cost_categories')
    op.drop_index(op.f('ix_cost_categories_id'), table_name='cost_categories')
    op.drop_table('cost_categories')
    # ### end Alembic commands ###
