"""add_custom_permissions

Revision ID: 370ee1ffa806
Revises: 7ac6cd70ce45
Create Date: 2026-01-26 15:04:17.632373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370ee1ffa806'
down_revision: Union[str, Sequence[str], None] = '7ac6cd70ce45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('custom_permissions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'custom_permissions')
    # ### end Alembic commands ###
