"""Add suppliers

Revision ID: 3835f626af6e
Revises: 41911e37f0fb
Create Date: 2026-01-26 20:44:24.560752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3835f626af6e'
down_revision: Union[str, Sequence[str], None] = '41911e37f0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('suppliers',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('contact_name', sa.String(), nullable=True),
    # sa.Column('email', sa.String(), nullable=True),
    # sa.Column('phone', sa.String(), nullable=True),
    # sa.Column('address', sa.Text(), nullable=True),
    # sa.Column('payment_method', sa.String(), nullable=True),
    # sa.Column('payment_details', sa.Text(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    # op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    # op.drop_index('ix_system_settings_key', table_name='system_settings')
    # op.drop_table('system_settings')
    # op.add_column('products', sa.Column('supplier_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'products', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'supplier_id')
    op.create_table('system_settings',
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('ix_system_settings_key', 'system_settings', ['key'], unique=False)
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
