"""add_min_stock_level

Revision ID: 41911e37f0fb
Revises: 370ee1ffa806
Create Date: 2026-01-26 17:09:06.046955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41911e37f0fb'
down_revision: Union[str, Sequence[str], None] = '370ee1ffa806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('min_stock_level', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'min_stock_level')
    # ### end Alembic commands ###
