"""Add supplier_id to stock_movements

Revision ID: 4e9bfd44ef10
Revises: 3835f626af6e
Create Date: 2026-01-26 20:48:36.816702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9bfd44ef10'
down_revision: Union[str, Sequence[str], None] = '3835f626af6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock_movements", schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_stock_movements_supplier_id', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_column('stock_movements', 'supplier_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    # ### end Alembic commands ###
