"""Decouple costs module

Revision ID: 755249c03e1d
Revises: d01ade3d96bf
Create Date: 2026-01-27 20:51:53.052732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755249c03e1d'
down_revision: Union[str, Sequence[str], None] = 'd01ade3d96bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'freight_cost')
    op.drop_column('products', 'landed_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('landed_cost', sa.FLOAT(), nullable=True))
    op.add_column('products', sa.Column('freight_cost', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
