"""add_fiscal_snapshot_to_documents

Revision ID: 983e7f8d9f7b
Revises: 3130a4f1fa4f
Create Date: 2026-01-27 23:31:07.823736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983e7f8d9f7b'
down_revision: Union[str, Sequence[str], None] = '3130a4f1fa4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('store_name', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('store_address', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('store_cuit', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('store_iva_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'store_iva_status')
    op.drop_column('documents', 'store_cuit')
    op.drop_column('documents', 'store_address')
    op.drop_column('documents', 'store_name')
    # ### end Alembic commands ###
