"""picking_and_barcodes

Revision ID: b206de9e9f1a
Revises: 426cb832c212
Create Date: 2026-01-25 21:52:18.089423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b206de9e9f1a'
down_revision: Union[str, Sequence[str], None] = '426cb832c212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_barcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_barcodes_barcode'), 'product_barcodes', ['barcode'], unique=True)
    op.create_index(op.f('ix_product_barcodes_id'), 'product_barcodes', ['id'], unique=False)
    op.create_index(op.f('ix_product_barcodes_product_id'), 'product_barcodes', ['product_id'], unique=False)
    op.create_table('pick_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_id')
    )
    op.create_index(op.f('ix_pick_tasks_id'), 'pick_tasks', ['id'], unique=False)
    op.create_table('pick_scan_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('barcode_scanned', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['pick_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pick_scan_events_id'), 'pick_scan_events', ['id'], unique=False)
    op.create_index(op.f('ix_pick_scan_events_task_id'), 'pick_scan_events', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pick_scan_events_task_id'), table_name='pick_scan_events')
    op.drop_index(op.f('ix_pick_scan_events_id'), table_name='pick_scan_events')
    op.drop_table('pick_scan_events')
    op.drop_index(op.f('ix_pick_tasks_id'), table_name='pick_tasks')
    op.drop_table('pick_tasks')
    op.drop_index(op.f('ix_product_barcodes_product_id'), table_name='product_barcodes')
    op.drop_index(op.f('ix_product_barcodes_id'), table_name='product_barcodes')
    op.drop_index(op.f('ix_product_barcodes_barcode'), table_name='product_barcodes')
    op.drop_table('product_barcodes')
    # ### end Alembic commands ###
