"""add_product_uom_fixed

Revision ID: cd5fee14e6a9
Revises: bd5658c44825
Create Date: 2026-01-26 23:45:01.554348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5fee14e6a9'
down_revision: Union[str, Sequence[str], None] = 'bd5658c44825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unit_of_measure', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'unit_of_measure')
    # ### end Alembic commands ###
