"""Add cost fields to product

Revision ID: d01ade3d96bf
Revises: d5f4a4e5dfb8
Create Date: 2026-01-27 20:32:58.295669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01ade3d96bf'
down_revision: Union[str, Sequence[str], None] = 'd5f4a4e5dfb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cost_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('freight_cost', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('landed_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'landed_cost')
    op.drop_column('products', 'freight_cost')
    op.drop_column('products', 'cost_price')
    # ### end Alembic commands ###
