"""product suppliers m2m

Revision ID: d5f4a4e5dfb8
Revises: d38a423a598a
Create Date: 2026-01-27 19:30:56.079593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f4a4e5dfb8'
down_revision: Union[str, Sequence[str], None] = 'd38a423a598a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_supplier_association',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'supplier_id')
    )

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('supplier_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('supplier_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('fk_products_supplier', 'products', 'suppliers', ['supplier_id'], ['id'])
    op.drop_table('product_supplier_association')
    # ### end Alembic commands ###
