"""add_is_inventory_tracked

Revision ID: dc63abba97ea
Revises: 983e7f8d9f7b
Create Date: 2026-02-08 17:13:09.985306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc63abba97ea'
down_revision: Union[str, Sequence[str], None] = '983e7f8d9f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_inventory_tracked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_inventory_tracked')
    # ### end Alembic commands ###
